services:
  aurora_db:
    image: postgres:latest
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: aurora
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  postgres: