server:
  port: 4812
  servlet:
    context-path: /api

spring:
  r2dbc:
    url: r2dbc:h2:mem:///auroradb
    username: aurora_user
    password: aurora_password
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  devtools:
    add-properties: true

aurora-api:
  base-url: http://127.0.0.1:8082

logging:
  level:
    io.r2dbc.postgresql: INFO
    org.springframework.r2dbc.core: INFO
    org.springframework.data.r2dbc: INFO
    reactor: INFO